<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core as cores;

	class Userwishlistproducts {
		private $_id;
		private $_idUserwishlist;
		private $_idProduct;
		private $_title;
		private $_description;
		private $_price;
		private $_creationdate;
		private $_queryBuilder;

		public function __construct($id = "", $idUserwishlist = "", $idProduct = "", $title = "", $description = "", $price = "", $creationdate = ""){
			$this->_queryBuilder = new cores\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "idUserwishlist" => $idUserwishlist, "idProduct" => $idProduct, "title" => $title, "description" => $description, "price" => $price, "creationdate" => $creationdate));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getIdUserwishlist() {
			return $this->_idUserwishlist;
		}
		public function getIdProduct() {
			return $this->_idProduct;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getPrice() {
			return $this->_price;
		}
		public function getCreationdate() {
			return $this->_creationdate;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["idUserwishlist"]))
				$this->_idUserwishlist = $properties["idUserwishlist"];
			if(!empty($properties["idProduct"]))
				$this->_idProduct = $properties["idProduct"];
			if(!empty($properties["title"]))
				$this->_title = $properties["title"];
			if(!empty($properties["description"]))
				$this->_description = $properties["description"];
			if(!empty($properties["price"]))
				$this->_price = $properties["price"];
			if(!empty($properties["creationdate"]))
				$this->_creationdate = $properties["creationdate"];
		}
	}
